name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm i -g wrangler
      - run: npm ci
      - run: npm run build
      - name: Deploy to Cloudflare Pages
        run: wrangler pages deploy --project-name ${{ secrets.CLOUDFLARE_PROJECT_NAME }} --branch master out
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
