name: github-pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Clone
        run: |
          git clone https://github.com/9sako6/9sako6.github.io.git
          cd 9sako6.github.io
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Add nojekyll
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
