name: github-pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/9sako6/9sako6.github.io.git app
          cd app
          git pull
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./app
      - name: Build
        run: |
          npm run build
        env:
          TZ: Asia/Tokyo
        working-directory: ./app
      - name: Add nojekyll
        run: |
          touch ./out/.nojekyll
        working-directory: ./app
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/out
