name: github-pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/9sako6/9sako6.github.io.git
          cd 9sako6.github.io
          git pull
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          yarn
        working-directory: ./9sako6.github.io
      - name: Build
        run: |
          yarn build
        working-directory: ./9sako6.github.io
      - name: Add nojekyll
        run: |
          touch ./out/.nojekyll
        working-directory: ./9sako6.github.io
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./9sako6.github.io/out
